//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BridgLoanTbl
    {
        public string University { get; set; }
        public string FeeParticular { get; set; }
        public string Amount { get; set; }
        public Nullable<int> Year { get; set; }
        public string Semester { get; set; }
        public string ProgramName { get; set; }
        public int Id { get; set; }
    }
}
