//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hostel_Master
    {
        public int Hostel_ID { get; set; }
        public string Hostel_Name { get; set; }
        public string Gender { get; set; }
        public string Incharge_Name { get; set; }
        public string Incharge_Email { get; set; }
        public string Incharge_Number { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string State { get; set; }
        public string Category { get; set; }
    }
}
