//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hostel_Allocation
    {
        public int Id { get; set; }
        public Nullable<int> Hostel_ID { get; set; }
        public string floor { get; set; }
        public string Room_Type { get; set; }
        public string Room_Number { get; set; }
        public string Enrollment_ID { get; set; }
        public Nullable<int> Bed_Number { get; set; }
        public Nullable<System.DateTime> Allocation_Date { get; set; }
        public string Allocated_By { get; set; }
        public Nullable<System.DateTime> Allocation_Start { get; set; }
        public Nullable<System.DateTime> Allocation_End { get; set; }
        public Nullable<bool> Allocation_Status { get; set; }
        public string Prev_Room { get; set; }
        public Nullable<int> Prev_Hostel { get; set; }
        public string EmailID { get; set; }
    }
}
