//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostelFeesTbl
    {
        public int HostelFeeID { get; set; }
        public string University { get; set; }
        public Nullable<int> HostelID { get; set; }
        public string RoomType { get; set; }
        public Nullable<decimal> RoomAmount { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Year { get; set; }
        public string YearPeriod { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> TotalRooms { get; set; }
        public string HostelName { get; set; }
        public Nullable<int> AvailableRooms { get; set; }
    }
}
