//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessFeesTbl
    {
        public int MessFeeID { get; set; }
        public string University { get; set; }
        public Nullable<int> MessID { get; set; }
        public string MealPlan { get; set; }
        public Nullable<decimal> MessAmount { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Year { get; set; }
        public string YearPeriod { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
