//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FEEEntities1 : DbContext
    {
        public FEEEntities1()
            : base("name=FEEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BridgLoanTbl> BridgLoanTbls { get; set; }
        public virtual DbSet<Hostel_Allocation> Hostel_Allocation { get; set; }
        public virtual DbSet<Hostel_Master> Hostel_Master { get; set; }
        public virtual DbSet<HostelFeesTbl> HostelFeesTbls { get; set; }
        public virtual DbSet<MessFeesTbl> MessFeesTbls { get; set; }
        public virtual DbSet<PenaltyDetailsTbl> PenaltyDetailsTbls { get; set; }
        public virtual DbSet<PersonalDetailsTbl> PersonalDetailsTbls { get; set; }
        public virtual DbSet<ProgramTbl> ProgramTbls { get; set; }
        public virtual DbSet<ReRegistrationDetailsTbl> ReRegistrationDetailsTbls { get; set; }
        public virtual DbSet<SemesterFeesTbl> SemesterFeesTbls { get; set; }
        public virtual DbSet<StudentProgramTbl> StudentProgramTbls { get; set; }
        public virtual DbSet<StudentTbl> StudentTbls { get; set; }
        public virtual DbSet<TblCashOnDeposit> TblCashOnDeposits { get; set; }
        public virtual DbSet<TblDue> TblDues { get; set; }
        public virtual DbSet<TblFeeDetail> TblFeeDetails { get; set; }
        public virtual DbSet<TblLogin> TblLogins { get; set; }
        public virtual DbSet<TransportTbl> TransportTbls { get; set; }
    }
}
