//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDetailsTbl
    {
        public int Id { get; set; }
        public string AdmitCardNo { get; set; }
        public string EnrollmentNo { get; set; }
        public string AdmissionNo { get; set; }
        public string RegistrationNo { get; set; }
        public string StudentName { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public Nullable<int> Father_Age { get; set; }
        public Nullable<int> Mother_Age { get; set; }
        public Nullable<int> LocalGuardianAge { get; set; }
        public Nullable<int> AdmissionYear { get; set; }
        public string Program { get; set; }
        public string Branch { get; set; }
        public Nullable<int> Year { get; set; }
        public string RoomNo { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Gender { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PresentResidentialAddress { get; set; }
        public string StudentAddress_Communication { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string Father_Mobile_No { get; set; }
        public string Mother_Mobile_No { get; set; }
        public string StudentContactNo { get; set; }
        public string FathersEmail { get; set; }
        public string MothersEmail { get; set; }
        public string StudentEmail { get; set; }
        public string LocalGuardianName { get; set; }
        public string LocalGuardianResidentialAddress { get; set; }
        public string LocalGuardianContactNo { get; set; }
        public string LocalGuardianEmail { get; set; }
        public string LocalGuardianRelationWithStudent { get; set; }
        public string LocalGuardianOccupation { get; set; }
        public string Parents_Income_Category { get; set; }
        public string Work_Experience { get; set; }
        public string Past_Health_History { get; set; }
        public string Details_Of_Past_Health_History { get; set; }
        public string AllergyNames { get; set; }
        public string History_Of_Substance_Allergy { get; set; }
        public string Caste { get; set; }
        public string AadharNumber { get; set; }
        public string stu_whatsappnum { get; set; }
        public string Batch { get; set; }
        public string University { get; set; }
        public string History_of_drug_allergy { get; set; }
        public string Student_Name__as_per_10th_grade_sheet_ { get; set; }
    }
}
