//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramTbl
    {
        public int ProgramID { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public string ProgramName { get; set; }
        public string ProgramShortForm { get; set; }
        public string Batch { get; set; }
        public string SchoolDept { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ProgramStaff { get; set; }
        public Nullable<int> YearProgram { get; set; }
    }
}
