//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReRegistrationDetailsTbl
    {
        public int ReRegID { get; set; }
        public string AppNo { get; set; }
        public string EnrollmentNo { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string Batch { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Subject { get; set; }
    }
}
