//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemesterFeesTbl
    {
        public int FeeID { get; set; }
        public string University { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string FeeParticular { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Semester { get; set; }
        public string ProgramName { get; set; }
    }
}
