//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentProgramTbl
    {
        public int StudentProgramID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string AppNo { get; set; }
        public string EnrollmentNo { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string Batch { get; set; }
        public string University { get; set; }
        public Nullable<int> CurrentSemester { get; set; }
        public string ProgramName { get; set; }
    }
}
