//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDue
    {
        public int Id { get; set; }
        public string University { get; set; }
        public string EnrollmentNo { get; set; }
        public string ApplicationNo { get; set; }
        public string StudentId { get; set; }
        public string DuePurpose { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
