//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFeeDetail
    {
        public int Id { get; set; }
        public string USERID { get; set; }
        public string Name { get; set; }
        public string EnrollmentNo { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string ProgramName { get; set; }
        public string FeeParticular { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public Nullable<bool> Paid { get; set; }
        public string TransactionOrder { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public string OrderNo { get; set; }
        public string Category { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CurrentSemester { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string HostelName { get; set; }
        public string RoomType { get; set; }
        public Nullable<int> NoOfPapers { get; set; }
    }
}
